import type { AntdvMenuItem } from './interface'

export const componentLocales = {
  '/components/overview': { 'zh-CN': '概览', 'en-US': 'Overview' },
  '/components/changelog': { 'zh-CN': '更新日志', 'en-US': 'Changelog' },
  // General
  'general': { 'zh-CN': '通用', 'en-US': 'General' },
  '/components/button': { 'zh-CN': '按钮', 'en-US': 'Button' },
  '/components/float-button': { 'zh-CN': '悬浮按钮', 'en-US': 'FloatButton' },
  '/components/icon': { 'zh-CN': '图标', 'en-US': 'Icon' },
  '/components/typography': { 'zh-CN': '排版', 'en-US': 'Typography' },
  // Layout
  'layout': { 'zh-CN': '布局', 'en-US': 'Layout' },
  '/components/divider': { 'zh-CN': '分割线', 'en-US': 'Divider' },
  '/components/flex': { 'zh-CN': '弹性布局', 'en-US': 'Flex' },
  '/components/grid': { 'zh-CN': '栅格', 'en-US': 'Grid' },
  '/components/layout': { 'zh-CN': '布局', 'en-US': 'Layout' },
  '/components/masonry': { 'zh-CN': '瀑布流', 'en-US': 'Masonry' },
  '/components/space': { 'zh-CN': '间距', 'en-US': 'Space' },
  '/components/splitter': { 'zh-CN': '面板分割', 'en-US': 'Splitter' },
  // Navigation
  'navigation': { 'zh-CN': '导航', 'en-US': 'Navigation' },
  '/components/anchor': { 'zh-CN': '锚点', 'en-US': 'Anchor' },
  '/components/breadcrumb': { 'zh-CN': '面包屑', 'en-US': 'Breadcrumb' },
  '/components/dropdown': { 'zh-CN': '下拉菜单', 'en-US': 'Dropdown' },
  '/components/menu': { 'zh-CN': '导航菜单', 'en-US': 'Menu' },
  '/components/pagination': { 'zh-CN': '分页', 'en-US': 'Pagination' },
  '/components/steps': { 'zh-CN': '步骤条', 'en-US': 'Steps' },
  '/components/tabs': { 'zh-CN': '标签页', 'en-US': 'Tabs' },
  // Data Entry
  'data-entry': { 'zh-CN': '数据录入', 'en-US': 'Data Entry' },
  '/components/auto-complete': { 'zh-CN': '自动完成', 'en-US': 'AutoComplete' },
  '/components/cascader': { 'zh-CN': '级联选择', 'en-US': 'Cascader' },
  '/components/checkbox': { 'zh-CN': '多选框', 'en-US': 'Checkbox' },
  '/components/color-picker': { 'zh-CN': '颜色选择器', 'en-US': 'ColorPicker' },
  '/components/date-picker': { 'zh-CN': '日期选择器', 'en-US': 'DatePicker' },
  '/components/form': { 'zh-CN': '表单', 'en-US': 'Form' },
  '/components/input': { 'zh-CN': '输入框', 'en-US': 'Input' },
  '/components/input-number': { 'zh-CN': '数字输入框', 'en-US': 'InputNumber' },
  '/components/mentions': { 'zh-CN': '提及', 'en-US': 'Mentions' },
  '/components/radio': { 'zh-CN': '单选框', 'en-US': 'Radio' },
  '/components/rate': { 'zh-CN': '评分', 'en-US': 'Rate' },
  '/components/select': { 'zh-CN': '选择器', 'en-US': 'Select' },
  '/components/slider': { 'zh-CN': '滑动输入条', 'en-US': 'Slider' },
  '/components/switch': { 'zh-CN': '开关', 'en-US': 'Switch' },
  '/components/time-picker': { 'zh-CN': '时间选择器', 'en-US': 'TimePicker' },
  '/components/transfer': { 'zh-CN': '穿梭框', 'en-US': 'Transfer' },
  '/components/tree-select': { 'zh-CN': '树选择', 'en-US': 'TreeSelect' },
  '/components/upload': { 'zh-CN': '上传', 'en-US': 'Upload' },
  // Data Display
  'data-display': { 'zh-CN': '数据展示', 'en-US': 'Data Display' },
  '/components/avatar': { 'zh-CN': '头像', 'en-US': 'Avatar' },
  '/components/badge': { 'zh-CN': '徽标数', 'en-US': 'Badge' },
  '/components/calendar': { 'zh-CN': '日历', 'en-US': 'Calendar' },
  '/components/card': { 'zh-CN': '卡片', 'en-US': 'Card' },
  '/components/carousel': { 'zh-CN': '走马灯', 'en-US': 'Carousel' },
  '/components/collapse': { 'zh-CN': '折叠面板', 'en-US': 'Collapse' },
  '/components/descriptions': { 'zh-CN': '描述列表', 'en-US': 'Descriptions' },
  '/components/empty': { 'zh-CN': '空状态', 'en-US': 'Empty' },
  '/components/image': { 'zh-CN': '图片', 'en-US': 'Image' },
  '/components/list': { 'zh-CN': '列表', 'en-US': 'List' },
  '/components/popover': { 'zh-CN': '气泡卡片', 'en-US': 'Popover' },
  '/components/qr-code': { 'zh-CN': '二维码', 'en-US': 'QRCode' },
  '/components/segmented': { 'zh-CN': '分段控制器', 'en-US': 'Segmented' },
  '/components/statistic': { 'zh-CN': '统计数值', 'en-US': 'Statistic' },
  '/components/table': { 'zh-CN': '表格', 'en-US': 'Table' },
  '/components/tag': { 'zh-CN': '标签', 'en-US': 'Tag' },
  '/components/timeline': { 'zh-CN': '时间轴', 'en-US': 'Timeline' },
  '/components/tooltip': { 'zh-CN': '文字提示', 'en-US': 'Tooltip' },
  '/components/tour': { 'zh-CN': '漫游导览', 'en-US': 'Tour' },
  '/components/tree': { 'zh-CN': '树形控件', 'en-US': 'Tree' },
  // Feedback
  'feedback': { 'zh-CN': '反馈', 'en-US': 'Feedback' },
  '/components/alert': { 'zh-CN': '警告提示', 'en-US': 'Alert' },
  '/components/drawer': { 'zh-CN': '抽屉', 'en-US': 'Drawer' },
  '/components/message': { 'zh-CN': '全局提示', 'en-US': 'Message' },
  '/components/modal': { 'zh-CN': '对话框', 'en-US': 'Modal' },
  '/components/notification': { 'zh-CN': '通知提醒框', 'en-US': 'Notification' },
  '/components/popconfirm': { 'zh-CN': '气泡确认框', 'en-US': 'Popconfirm' },
  '/components/progress': { 'zh-CN': '进度条', 'en-US': 'Progress' },
  '/components/result': { 'zh-CN': '结果', 'en-US': 'Result' },
  '/components/skeleton': { 'zh-CN': '骨架屏', 'en-US': 'Skeleton' },
  '/components/spin': { 'zh-CN': '加载中', 'en-US': 'Spin' },
  '/components/watermark': { 'zh-CN': '水印', 'en-US': 'Watermark' },
  // Other
  'other': { 'zh-CN': '其他', 'en-US': 'Other' },
  '/components/affix': { 'zh-CN': '固钉', 'en-US': 'Affix' },
  '/components/app': { 'zh-CN': '应用配置', 'en-US': 'App' },
  '/components/config-provider': { 'zh-CN': '全局化配置', 'en-US': 'ConfigProvider' },
  '/components/_util': { 'zh-CN': '工具', 'en-US': 'Util' },
}

export const components: AntdvMenuItem[] = [
  { key: '/components/overview', label: 'Overview' },
  { key: '/components/changelog', label: 'Changelog', tag: 'v6.1.1' },
  {
    key: 'general',
    label: 'General',
    type: 'group',
    children: [
      { key: '/components/button', label: 'Button' },
      { key: '/components/float-button', label: 'FloatButton' },
      { key: '/components/icon', label: 'Icon' },
      { key: '/components/typography', label: 'Typography' },
    ],
  },
  {
    key: 'layout',
    label: 'Layout',
    type: 'group',
    children: [
      { key: '/components/divider', label: 'Divider' },
      { key: '/components/flex', label: 'Flex' },
      { key: '/components/grid', label: 'Grid' },
      { key: '/components/layout', label: 'Layout' },
      { key: '/components/masonry', label: 'Masonry' },
      { key: '/components/space', label: 'Space' },
      { key: '/components/splitter', label: 'Splitter' },
    ],
  },
  {
    key: 'navigation',
    label: 'Navigation',
    type: 'group',
    children: [
      { key: '/components/anchor', label: 'Anchor' },
      { key: '/components/breadcrumb', label: 'Breadcrumb' },
      { key: '/components/dropdown', label: 'Dropdown' },
      { key: '/components/menu', label: 'Menu' },
      { key: '/components/pagination', label: 'Pagination' },
      { key: '/components/steps', label: 'Steps' },
      { key: '/components/tabs', label: 'Tabs' },
    ],
  },
  {
    key: 'data-entry',
    label: 'Data Entry',
    type: 'group',
    children: [
      { key: '/components/auto-complete', label: 'AutoComplete' },
      { key: '/components/cascader', label: 'Cascader' },
      { key: '/components/checkbox', label: 'Checkbox' },
      { key: '/components/color-picker', label: 'ColorPicker' },
      { key: '/components/date-picker', label: 'DatePicker' },
      { key: '/components/form', label: 'Form' },
      { key: '/components/input', label: 'Input' },
      { key: '/components/input-number', label: 'InputNumber' },
      { key: '/components/mentions', label: 'Mentions' },
      { key: '/components/radio', label: 'Radio' },
      { key: '/components/rate', label: 'Rate' },
      { key: '/components/select', label: 'Select' },
      { key: '/components/slider', label: 'Slider' },
      { key: '/components/switch', label: 'Switch' },
      { key: '/components/time-picker', label: 'TimePicker' },
      { key: '/components/transfer', label: 'Transfer' },
      { key: '/components/tree-select', label: 'TreeSelect' },
      { key: '/components/upload', label: 'Upload' },
    ],
  },
  {
    key: 'data-display',
    label: 'Data Display',
    type: 'group',
    children: [
      { key: '/components/avatar', label: 'Avatar' },
      { key: '/components/badge', label: 'Badge' },
      { key: '/components/calendar', label: 'Calendar' },
      { key: '/components/card', label: 'Card' },
      { key: '/components/carousel', label: 'Carousel' },
      { key: '/components/collapse', label: 'Collapse' },
      { key: '/components/descriptions', label: 'Descriptions' },
      { key: '/components/empty', label: 'Empty' },
      { key: '/components/image', label: 'Image' },
      // { key: '/components/list', label: 'List', tag: 'DEPRECATED' },
      { key: '/components/popover', label: 'Popover' },
      { key: '/components/qr-code', label: 'QRCode' },
      { key: '/components/segmented', label: 'Segmented' },
      { key: '/components/statistic', label: 'Statistic' },
      { key: '/components/table', label: 'Table' },
      { key: '/components/tag', label: 'Tag' },
      { key: '/components/timeline', label: 'Timeline' },
      { key: '/components/tooltip', label: 'Tooltip' },
      { key: '/components/tour', label: 'Tour' },
      { key: '/components/tree', label: 'Tree' },
    ],
  },
  {
    key: 'feedback',
    label: 'Feedback',
    type: 'group',
    children: [
      { key: '/components/alert', label: 'Alert' },
      { key: '/components/drawer', label: 'Drawer' },
      { key: '/components/message', label: 'Message' },
      { key: '/components/modal', label: 'Modal' },
      { key: '/components/notification', label: 'Notification' },
      { key: '/components/popconfirm', label: 'Popconfirm' },
      { key: '/components/progress', label: 'Progress' },
      { key: '/components/result', label: 'Result' },
      { key: '/components/skeleton', label: 'Skeleton' },
      { key: '/components/spin', label: 'Spin' },
      { key: '/components/watermark', label: 'Watermark' },
    ],
  },
  {
    key: 'other',
    label: 'Other',
    type: 'group',
    children: [
      { key: '/components/affix', label: 'Affix' },
      { key: '/components/app', label: 'App' },
      { key: '/components/config-provider', label: 'ConfigProvider' },
    ],
  },
]
